import { Toaster } from 'sonner'
import './globals.css'

export const metadata = {
  title: 'Cooperativa Paraja La Virgen',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body data-theme="corporate">
        {children}
        <Toaster richColors closeButton />
      </body>
    </html>
  )
}
